// 领养申请相关常量

export const FETCH_ADOPTION_LIST_REQUEST = 'FETCH_ADOPTION_LIST_REQUEST';
export const FETCH_ADOPTION_LIST_SUCCESS = 'FETCH_ADOPTION_LIST_SUCCESS';
export const FETCH_ADOPTION_LIST_FAILURE = 'FETCH_ADOPTION_LIST_FAILURE';

export const SUBMIT_ADOPTION_REQUEST = 'SUBMIT_ADOPTION_REQUEST';
export const SUBMIT_ADOPTION_SUCCESS = 'SUBMIT_ADOPTION_SUCCESS';
export const SUBMIT_ADOPTION_FAILURE = 'SUBMIT_ADOPTION_FAILURE';

export const AUDIT_ADOPTION_REQUEST = 'AUDIT_ADOPTION_REQUEST';
export const AUDIT_ADOPTION_SUCCESS = 'AUDIT_ADOPTION_SUCCESS';
export const AUDIT_ADOPTION_FAILURE = 'AUDIT_ADOPTION_FAILURE';