// 猫猫档案相关常量

export const FETCH_CAT_LIST_REQUEST = 'FETCH_CAT_LIST_REQUEST';
export const FETCH_CAT_LIST_SUCCESS = 'FETCH_CAT_LIST_SUCCESS';
export const FETCH_CAT_LIST_FAILURE = 'FETCH_CAT_LIST_FAILURE';

export const ADD_CAT_REQUEST = 'ADD_CAT_REQUEST';
export const ADD_CAT_SUCCESS = 'ADD_CAT_SUCCESS';
export const ADD_CAT_FAILURE = 'ADD_CAT_FAILURE';

export const EDIT_CAT_REQUEST = 'EDIT_CAT_REQUEST';
export const EDIT_CAT_SUCCESS = 'EDIT_CAT_SUCCESS';
export const EDIT_CAT_FAILURE = 'EDIT_CAT_FAILURE';