// 留言反馈相关常量

export const FETCH_FEEDBACK_LIST_REQUEST = 'FETCH_FEEDBACK_LIST_REQUEST';
export const FETCH_FEEDBACK_LIST_SUCCESS = 'FETCH_FEEDBACK_LIST_SUCCESS';
export const FETCH_FEEDBACK_LIST_FAILURE = 'FETCH_FEEDBACK_LIST_FAILURE';

export const SUBMIT_FEEDBACK_REQUEST = 'SUBMIT_FEEDBACK_REQUEST';
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS';
export const SUBMIT_FEEDBACK_FAILURE = 'SUBMIT_FEEDBACK_FAILURE';

export const REPLY_FEEDBACK_REQUEST = 'REPLY_FEEDBACK_REQUEST';
export const REPLY_FEEDBACK_SUCCESS = 'REPLY_FEEDBACK_SUCCESS';
export const REPLY_FEEDBACK_FAILURE = 'REPLY_FEEDBACK_FAILURE';