// 救助信息相关常量

export const FETCH_RESCUE_LIST_REQUEST = 'FETCH_RESCUE_LIST_REQUEST';
export const FETCH_RESCUE_LIST_SUCCESS = 'FETCH_RESCUE_LIST_SUCCESS';
export const FETCH_RESCUE_LIST_FAILURE = 'FETCH_RESCUE_LIST_FAILURE';

export const PUBLISH_RESCUE_REQUEST = 'PUBLISH_RESCUE_REQUEST';
export const PUBLISH_RESCUE_SUCCESS = 'PUBLISH_RESCUE_SUCCESS';
export const PUBLISH_RESCUE_FAILURE = 'PUBLISH_RESCUE_FAILURE';

export const AUDIT_RESCUE_REQUEST = 'AUDIT_RESCUE_REQUEST';
export const AUDIT_RESCUE_SUCCESS = 'AUDIT_RESCUE_SUCCESS';
export const AUDIT_RESCUE_FAILURE = 'AUDIT_RESCUE_FAILURE';

export const UPDATE_RESCUE_STATUS_REQUEST = 'UPDATE_RESCUE_STATUS_REQUEST';
export const UPDATE_RESCUE_STATUS_SUCCESS = 'UPDATE_RESCUE_STATUS_SUCCESS';
export const UPDATE_RESCUE_STATUS_FAILURE = 'UPDATE_RESCUE_STATUS_FAILURE';